# Site settings
title: Into the Darkness
email: bdetweiler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "When I have clarified and exhausted a subject, then I turn away from it, in order to go into darkness again." -- Carl Friedrich Gauss
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: detweiler
github_username:  bdetweiler

# Build settings
markdown: kramdown
